FROM node:alpine AS development
LABEL authors="andu"

WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build api-gateway

FROM node:alpine AS production
ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install --omit=dev
COPY . .
COPY --from=development /usr/src/app/dist ./dist
CMD ["node", "dist/apps/api-gateway/main"]
